apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: tasks
  name: tasks
spec:
  output:
    to:
      kind: ImageStreamTag
      name: GUID-tasks:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jboss-eap72-openshift:1.0
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
